#!/bin/bash
#SBATCH -o /scratch/nunger/nathan.out -e /scratch/nunger/nathan.err
# One Eccentric vs Two circular
source ~/.bashrc
module add spack
module add gcc
module add python/3.6.5
for dfile in {1..15}
do
    for model in {1..2}
    do
        for iter in {1..3}
        do
            python ../ppc_nathan.py -dfile $dfile -model $model --cluster
        done
    done
done