#!/bin/bash
#SBATCH -p p4 -n 16 -o /scratch/nunger/nathan.out -e /scratch/nunger/nathan.err
# One Eccentric vs Two circular
source ~/.bashrc
module add spack
module add gcc
module add python/2.7.15
module add openmpi/2.1.0
module add mpi4py/1.3.1
for dfile in {31..40}
do
    for model in {3..3}
    do
        for iter in {1..5}
        do
            srun --mpi=pmi2 python ../ppc_nathan.py -dfile $dfile -model $model -nlive 50 --cluster
        done
    done
done