#!/bin/bash
#SBATCH -p p4 -n 16 -o /scratch/nunger/nathan.out -e /scratch/nunger/nathan.err
# One Eccentric vs Two circular
source ~/.bashrc
module add spack
module add gcc
module add python/2.7.15
module add openmpi/2.1.0
module add mpi4py/1.3.1
for i in {1..10}
do
    srun --mpi=pmi2 python ppc_rv.py -model 3 -nlive 50 -nrep 5 --cluster
done