#!/bin/bash
#SBATCH -p p4 -n 16 -o /scratch/nunger/eprv.out -e /scratch/nunger/eprv.err
# Extremely Presice Evidence Challenge
# Dataset 2. 0 and 1 Planet.
source ~/.bashrc
module add spack
module add gcc
module add python/2.7.15
module add openmpi/2.1.0
module add mpi4py/1.3.1
for iter in {1..6}
do
    srun --mpi=pmi2 python ../ppc_eprv3_cluster.py -n 1 -nlive 2000 -dfile 6 --narrow
done