#!/bin/bash
#SBATCH -o /scratch/nunger/eprv.out -e /scratch/nunger/eprv.err
# Extremely Presice Evidence Challenge
# Dataset 5. All planet models.
source ~/.bashrc
module add spack
module add gcc
module add python/3.6.5
for n in {2..2}
do
    for iter in {1..12}
    do
        python ../ppc_eprv3_cluster.py -n $n -dfile 5
    done
done