#!/bin/bash
#SBATCH -p p4 -n 24 -o /scratch/nunger/eprv.out -e /scratch/nunger/eprv.err
# Extremely Presice Evidence Challenge
# Dataset 1. All planet models.
source ~/.bashrc
module add spack
module add gcc
module add python/2.7.15
module add openmpi/2.1.0
for n in {1..1}
do
    for iter in {1..1}
    do
        srun --mpi=pmi2 python ../ppc_eprv3_cluster.py -n $n -dfile 1
    done
done