#!/bin/bash
#SBATCH -p p4 -n 8 -o /scratch/nunger/my.stdout0 -e /scratch/nunger/my.stderr0
# run the simulation
source ~/.bashrc
module add spack
module add gcc
module add python/2.7.15
module add openmpi/2.1.0
module add mpi4py/1.3.1
nano=$(date +%N)
srun --mpi=pmi2 python ppc_harps_cluster_old.py -n 0 -nlive 25 --save --cluster -nano $nano