#!/bin/bash
#SBATCH -p p4 -n 8 -o /scratch/nunger/nathan.out -e /scratch/nunger/nathan.err
# One Eccentric vs Two circular
source ~/.bashrc
module add spack
module add gcc
module add python/2.7.15
module add openmpi/2.1.0
module add mpi4py/1.3.1
srun --mpi=pmi2 python ../../ppc_nathan.py -dfile 5 -model 3 -nlive 25 --cluster